/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubricsevaluation;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import java.awt.Toolkit;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdullah
 */
public class Main extends javax.swing.JFrame {

    private static final int WIDTH = Toolkit.getDefaultToolkit().getScreenSize().width;
    private static final int HEIGHT = Toolkit.getDefaultToolkit().getScreenSize().height;
    //Few Colors
    private static final Color brightLilac = new Color(205, 132, 241);
    private static final Color prettyPlease = new Color(255, 204, 204);
    private static final Color lightRed = new Color(255, 77, 77);
    private static final Color lightPurple = new Color(197, 108, 240);
    private static final Color white = new Color(255, 255, 255);
    private static final Color electricBlue = new Color(126, 255, 245);

    private final DefaultListModel courseListModel = new DefaultListModel();
    private MainSystem system = MainSystem.getInstance();
    private int marks = 0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        this.setLocation((WIDTH - this.getWidth()) / 2, (HEIGHT - this.getHeight()) / 2);

        //Date and time
        SimpleDateFormat date = new SimpleDateFormat("EEEE dd");
        SimpleDateFormat time = new SimpleDateFormat("hh:mm a");
        dateLabel.setText(date.format(new Date()));
        this.setVisible(true);
        system.loadData();
        system = MainSystem.getInstance();
        System.out.println(system.getCourses());
        System.out.println(system.getStudents());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new RoundedPanel(30);
        bar = new RoundedPanel(30);
        logoPanel = new RoundedPanel(30);
        logoLabel = new javax.swing.JLabel();
        homeButtonPanel = new RoundedPanel(30);
        homeButtonLabel = new javax.swing.JLabel();
        courseButtonPanel = new RoundedPanel(30);
        courseButtonLabel = new javax.swing.JLabel();
        studentButtonPanel = new RoundedPanel(30);
        studentButtonLabel = new javax.swing.JLabel();
        assessmentButtonPanel = new RoundedPanel(30);
        assessmentButtonLabel = new javax.swing.JLabel();
        stack = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        userinfo = new RoundedPanel(30);
        displayPicture = new javax.swing.JLabel();
        clockPanel = new RoundedPanel(30);
        dateLabel = new javax.swing.JLabel();
        topStudentPanel = new RoundedPanel(30);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        center = new RoundedPanel(30);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        coursesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cloField = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        coursesList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fillLabel = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        addStudPanel = new RoundedPanel(30);
        jLabel10 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fatherField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cnicField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rollField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addStudentButton = new javax.swing.JButton();
        studentFillLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentListPanel = new RoundedPanel(30);
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        assessmentPanel = new javax.swing.JPanel();
        addQuestionPanel = new RoundedPanel(30);
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        questionField = new javax.swing.JTextField();
        marksBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        coursesBox = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        rubricField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cloComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rubrics Evaluation");
        setUndecorated(true);
        setResizable(false);

        back.setBackground(new java.awt.Color(246, 246, 247));
        back.setForeground(new java.awt.Color(255, 255, 255));

        bar.setBackground(lightPurple);
        bar.setForeground(lightPurple);

        logoPanel.setBackground(lightPurple);
        logoPanel.setForeground(lightPurple);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-inspection-64.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homeButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        homeButtonPanel.setForeground(lightPurple);

        homeButtonLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-home-64.png"))); // NOI18N
        homeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeButtonPanelLayout = new javax.swing.GroupLayout(homeButtonPanel);
        homeButtonPanel.setLayout(homeButtonPanelLayout);
        homeButtonPanelLayout.setHorizontalGroup(
            homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeButtonPanelLayout.setVerticalGroup(
            homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        courseButtonPanel.setBackground(lightPurple);
        courseButtonPanel.setForeground(lightPurple);

        courseButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-course-64.png"))); // NOI18N
        courseButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout courseButtonPanelLayout = new javax.swing.GroupLayout(courseButtonPanel);
        courseButtonPanel.setLayout(courseButtonPanelLayout);
        courseButtonPanelLayout.setHorizontalGroup(
            courseButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        courseButtonPanelLayout.setVerticalGroup(
            courseButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentButtonPanel.setBackground(lightPurple);
        studentButtonPanel.setForeground(lightPurple);

        studentButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-person-64.png"))); // NOI18N
        studentButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout studentButtonPanelLayout = new javax.swing.GroupLayout(studentButtonPanel);
        studentButtonPanel.setLayout(studentButtonPanelLayout);
        studentButtonPanelLayout.setHorizontalGroup(
            studentButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentButtonPanelLayout.setVerticalGroup(
            studentButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assessmentButtonPanel.setBackground(lightPurple);
        assessmentButtonPanel.setForeground(lightPurple);

        assessmentButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/rsz_icons8-scorecard-64.png"))); // NOI18N
        assessmentButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assessmentButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout assessmentButtonPanelLayout = new javax.swing.GroupLayout(assessmentButtonPanel);
        assessmentButtonPanel.setLayout(assessmentButtonPanelLayout);
        assessmentButtonPanelLayout.setHorizontalGroup(
            assessmentButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assessmentButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        assessmentButtonPanelLayout.setVerticalGroup(
            assessmentButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assessmentButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(studentButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barLayout.createSequentialGroup()
                        .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assessmentButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(homeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assessmentButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoPanel.setOpaque(false);
        homeButtonPanel.setOpaque(false);
        courseButtonPanel.setOpaque(false);
        studentButtonPanel.setOpaque(false);
        assessmentButtonPanel.setOpaque(false);

        stack.setBackground(new java.awt.Color(255, 255, 255));
        stack.setForeground(new java.awt.Color(255, 255, 255));
        stack.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(246, 246, 247));

        userinfo.setBackground(white);
        userinfo.setForeground(white);

        displayPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-school-director-male-skin-type-7-64.png"))); // NOI18N

        clockPanel.setBackground(lightPurple);
        clockPanel.setForeground(lightPurple);

        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Sunday 04");

        javax.swing.GroupLayout clockPanelLayout = new javax.swing.GroupLayout(clockPanel);
        clockPanel.setLayout(clockPanelLayout);
        clockPanelLayout.setHorizontalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(dateLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        clockPanelLayout.setVerticalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(dateLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        topStudentPanel.setBackground(new java.awt.Color(255, 255, 255));
        topStudentPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("AnonyMous");

        javax.swing.GroupLayout topStudentPanelLayout = new javax.swing.GroupLayout(topStudentPanel);
        topStudentPanel.setLayout(topStudentPanelLayout);
        topStudentPanelLayout.setHorizontalGroup(
            topStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topStudentPanelLayout.createSequentialGroup()
                .addGroup(topStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topStudentPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(topStudentPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        topStudentPanelLayout.setVerticalGroup(
            topStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topStudentPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout userinfoLayout = new javax.swing.GroupLayout(userinfo);
        userinfo.setLayout(userinfoLayout);
        userinfoLayout.setHorizontalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(topStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(displayPicture))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        userinfoLayout.setVerticalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(displayPicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(topStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        clockPanel.setOpaque(false);
        topStudentPanel.setOpaque(false);
        jLabel19.setText(system.getTeacher().getName());

        center.setBackground(prettyPlease);
        center.setForeground(prettyPlease);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("See?The Home?That's the Dashboard.You're on it now.\n\n\nSee this board? Here you manage courses.\n\n\nHere you manage Students.\n\nAnd on the last you manage assessments.");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.setHorizontalScrollBar(null);

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(userinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        userinfo.setOpaque(false);
        center.setOpaque(false);

        stack.add(dashboard, "card2");

        coursesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Peace Sans", 1, 24)); // NOI18N
        jLabel1.setText("Add Course");

        jLabel2.setText("Course Title");

        jLabel7.setText("Course ID");

        idField.setToolTipText("");
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        cloField.setColumns(20);
        cloField.setRows(5);
        jScrollPane2.setViewportView(cloField);

        jLabel8.setText("CLOs");

        jLabel9.setForeground(prettyPlease);
        jLabel9.setText("Write one CLO in one line");

        jButton1.setBackground(lightPurple);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Course");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(coursesList);

        jButton2.setBackground(lightPurple);
        jButton2.setForeground(white);
        jButton2.setText("Save Changes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(lightPurple);
        jButton3.setForeground(this.white);
        jButton3.setText("Discard Changes");

        fillLabel.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout coursesPanelLayout = new javax.swing.GroupLayout(coursesPanel);
        coursesPanel.setLayout(coursesPanelLayout);
        coursesPanelLayout.setHorizontalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesPanelLayout.createSequentialGroup()
                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coursesPanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(coursesPanelLayout.createSequentialGroup()
                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coursesPanelLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(coursesPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(coursesPanelLayout.createSequentialGroup()
                                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(titleField)
                                                .addComponent(idField)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                                    .addGroup(coursesPanelLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(fillLabel))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        coursesPanelLayout.setVerticalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(coursesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        stack.add(coursesPanel, "card3");

        studentPanel.setBackground(new java.awt.Color(255, 255, 255));

        addStudPanel.setBackground(new java.awt.Color(126, 255, 245));
        addStudPanel.setForeground(new java.awt.Color(204, 255, 255));

        jLabel10.setText("Name");

        jLabel11.setText("Father");

        jLabel12.setText("CNIC");

        jLabel13.setText("Email");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Roll No.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        addStudentButton.setText("Add");
        addStudentButton.setBorderPainted(false);
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        studentFillLabel.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout addStudPanelLayout = new javax.swing.GroupLayout(addStudPanel);
        addStudPanel.setLayout(addStudPanelLayout);
        addStudPanelLayout.setHorizontalGroup(
            addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(fatherField)
                    .addComponent(cnicField)
                    .addComponent(emailField)
                    .addComponent(rollField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(addStudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(studentFillLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addStudentButton)
                        .addGap(15, 15, 15))
                    .addGroup(addStudPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        addStudPanelLayout.setVerticalGroup(
            addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fatherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cnicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rollField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentButton)
                    .addComponent(studentFillLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Peace Sans", 0, 18)); // NOI18N
        jLabel3.setText("Add Student");

        studentListPanel.setBackground(new java.awt.Color(126, 255, 245));
        studentListPanel.setForeground(new java.awt.Color(126, 255, 245));

        jScrollPane5.setViewportView(jList1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CLO", "Question", "Assessment", "Rubric Level"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jButton4.setText("Delete Selected");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Mark Assessments");

        jButton5.setText("Save");
        jButton5.setBorderPainted(false);

        javax.swing.GroupLayout studentListPanelLayout = new javax.swing.GroupLayout(studentListPanel);
        studentListPanel.setLayout(studentListPanelLayout);
        studentListPanelLayout.setHorizontalGroup(
            studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentListPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentListPanelLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4))
                        .addComponent(jScrollPane5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        studentListPanelLayout.setVerticalGroup(
            studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentListPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(addStudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(studentListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        addStudPanel.setOpaque(false);
        studentListPanel.setOpaque(false);

        stack.add(studentPanel, "card4");

        assessmentPanel.setBackground(new java.awt.Color(255, 255, 255));

        addQuestionPanel.setBackground(prettyPlease);
        addQuestionPanel.setForeground(prettyPlease);

        jLabel4.setText("Add Question");

        jLabel16.setText("Question");

        marksBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));

        jLabel17.setText("Total Marks: 0");

        coursesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesBoxActionPerformed(evt);
            }
        });

        jButton6.setBackground(lightPurple);
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add Question");

        rubricField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubricFieldActionPerformed(evt);
            }
        });

        jLabel18.setText("Rubric");

        jLabel20.setText("jLabel20");

        jLabel21.setText("CLO");

        javax.swing.GroupLayout addQuestionPanelLayout = new javax.swing.GroupLayout(addQuestionPanel);
        addQuestionPanel.setLayout(addQuestionPanelLayout);
        addQuestionPanelLayout.setHorizontalGroup(
            addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addQuestionPanelLayout.createSequentialGroup()
                .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(marksBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                                        .addComponent(rubricField)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6))
                                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(378, 378, 378)))
                                .addComponent(questionField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addQuestionPanelLayout.createSequentialGroup()
                                .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addQuestionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addQuestionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(59, 59, 59)))
                                .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(coursesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                                        .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addComponent(cloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        addQuestionPanelLayout.setVerticalGroup(
            addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addQuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addQuestionPanelLayout.createSequentialGroup()
                        .addComponent(questionField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(coursesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(marksBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(rubricField)))
                    .addComponent(jLabel20))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jButton7.setBackground(lightPurple);
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Save Changes");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout assessmentPanelLayout = new javax.swing.GroupLayout(assessmentPanel);
        assessmentPanel.setLayout(assessmentPanelLayout);
        assessmentPanelLayout.setHorizontalGroup(
            assessmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(addQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assessmentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(41, 41, 41))
        );
        assessmentPanelLayout.setVerticalGroup(
            assessmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(addQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        addQuestionPanel.setOpaque(false);

        stack.add(assessmentPanel, "card5");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bar.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        //back.setOpaque(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonLabelMouseClicked
        // TODO add your handling code here:

        //homeButtonPanel.setForeground(white);
        courseButtonPanel.setBackground(lightPurple);
        //courseButtonLabel.setForeground(lightPurple);

        studentButtonPanel.setBackground(lightPurple);
        //studentButtonLabel.setForeground(lightPurple);

        //assessmentButtonLabel.setForeground(lightPurple);
        assessmentButtonPanel.setBackground(lightPurple);
        homeButtonPanel.setBackground(white);

        //Changing the view
        stack.removeAll();
        stack.add(dashboard);
        stack.repaint();
        stack.revalidate();
    }//GEN-LAST:event_homeButtonLabelMouseClicked

    private void courseButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseButtonLabelMouseClicked
        // TODO add your handling code here:

        //courseButtonPanel.setForeground(white);
        homeButtonPanel.setBackground(lightPurple);
        //homeButtonPanel.setForeground(lightPurple);

        studentButtonPanel.setBackground(lightPurple);
        //studentButtonPanel.setForeground(lightPurple);

        //assessmentButtonPanel.setForeground(lightPurple);
        assessmentButtonPanel.setBackground(lightPurple);
        courseButtonPanel.setBackground(white);

        //Changing the view
        stack.removeAll();
        stack.add(coursesPanel);
        stack.repaint();
        stack.revalidate();
        clearCoursesList();
        loadCoursesList();
        this.addWindowListener(
                new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                system.saveData();
            }
        }
        );
    }//GEN-LAST:event_courseButtonLabelMouseClicked


    private void studentButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentButtonLabelMouseClicked
        // TODO add your handling code here:

        homeButtonPanel.setBackground(lightPurple);
        //homeButtonPanel.setForeground(lightPurple);

        courseButtonPanel.setBackground(lightPurple);
        //courseButtonPanel.setForeground(lightPurple);

        //assessmentButtonPanel.setForeground(lightPurple);
        assessmentButtonPanel.setBackground(lightPurple);
        studentButtonPanel.setBackground(white);
        stack.removeAll();
        stack.add(studentPanel);
        stack.repaint();
        stack.revalidate();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        clearCourseTable();
        for (int i = 0; i < system.getCourses().size(); i++) {
            model.addRow(new Object[]{false, system.getCourses().get(i).getTitle()});
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_studentButtonLabelMouseClicked

    private void clearCourseTable() {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
    }

    private void assessmentButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentButtonLabelMouseClicked
        // TODO add your handling code here:
        //assessmentButtonPanel.setForeground(white);
        assessmentButtonPanel.setBackground(white);

        homeButtonPanel.setBackground(lightPurple);
        //homeButtonPanel.setForeground(lightPurple);

        studentButtonPanel.setBackground(lightPurple);
        //studentButtonPanel.setForeground(lightPurple);

        courseButtonPanel.setBackground(lightPurple);
        //courseButtonPanel.setForeground(lightPurple);
        stack.removeAll();
        stack.add(assessmentPanel);
        stack.repaint();
        stack.revalidate();

        //
        DefaultComboBoxModel f = new DefaultComboBoxModel();
        f.addElement("Select Course");
        for (int i = 0; i < system.getCourses().size(); i++) {
            f.addElement(system.getCourses().get(i).getTitle());
        }
        coursesBox.setModel(f);

    }//GEN-LAST:event_assessmentButtonLabelMouseClicked

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fillLabel.setText("");
        String title = titleField.getText();
        String id = idField.getText();
        ArrayList<String> clos = new ArrayList<String>();
        Collections.addAll(clos, cloField.getText().split("\n"));
        if (title.isBlank() || id.isBlank() || clos.size() == 0) {
            fillLabel.setText("Fill all!");
            return;
        }
        system.addCourse(new Course(title, id, clos));
        clearCoursesList();
        loadCoursesList();
        System.out.println(system.getCourses());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearCoursesList() {
        coursesList.setModel(new DefaultListModel());
    }

    private void loadCoursesList() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < system.getCourses().size(); i++) {
            model.addElement(system.getCourses().get(i).getTitle());
        }
        coursesList.setModel(model);
    }
    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rubricFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubricFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rubricFieldActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
        studentFillLabel.setText("");
        String name = nameField.getText();
        String father = fatherField.getText();
        String cnic = cnicField.getText();
        String email = emailField.getText();
        String roll = rollField.getText();
        if (name.isBlank() || father.isBlank() || cnic.isBlank() || email.isBlank() || roll.isBlank()) {
            studentFillLabel.setText("Fill All!");
            return;
        }
        system.addStudent(new Student(roll, father, name, email, cnic));
        updateStudentList();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String registrationNumber = jList1.getSelectedValue().split(", ")[1];
        system.deleteStudent(registrationNumber);
        updateStudentList();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        system.saveData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void coursesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesBoxActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel f = new DefaultComboBoxModel();
        cloComboBox.setModel(f);
        String courseTitle = (String) coursesBox.getSelectedItem();
        for (int i = 0; i < system.getCourses().size(); i++) {
            if (system.getCourses().get(i).getTitle().equals(courseTitle)) {
                for (int ft = 0; ft < system.getCourses().get(i).getClos().size(); ft++) {
                    f.addElement(system.getCourses().get(i).getClos().get(ft));
                }
                break;
            }
        }
        cloComboBox.setModel(f);
    }//GEN-LAST:event_coursesBoxActionPerformed
    private void updateStudentList() {
        jList1.setModel(new DefaultListModel());
        DefaultListModel f = new DefaultListModel();
        for (int i = 0; i < system.getStudents().size(); i++) {
            f.addElement(system.getStudents().get(i).getName() + ", " + system.getStudents().get(i).getRegistrationNumber());
        }
        jList1.setModel(f);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addQuestionPanel;
    private javax.swing.JPanel addStudPanel;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JLabel assessmentButtonLabel;
    private javax.swing.JPanel assessmentButtonPanel;
    private javax.swing.JPanel assessmentPanel;
    private javax.swing.JPanel back;
    private javax.swing.JPanel bar;
    private javax.swing.JPanel center;
    private javax.swing.JComboBox<String> cloComboBox;
    private javax.swing.JTextArea cloField;
    private javax.swing.JPanel clockPanel;
    private javax.swing.JTextField cnicField;
    private javax.swing.JLabel courseButtonLabel;
    private javax.swing.JPanel courseButtonPanel;
    private javax.swing.JComboBox<String> coursesBox;
    private javax.swing.JList<String> coursesList;
    private javax.swing.JPanel coursesPanel;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel displayPicture;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fatherField;
    private javax.swing.JLabel fillLabel;
    private javax.swing.JLabel homeButtonLabel;
    private javax.swing.JPanel homeButtonPanel;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JComboBox<String> marksBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField questionField;
    private javax.swing.JTextField rollField;
    private javax.swing.JTextField rubricField;
    private javax.swing.JPanel stack;
    private javax.swing.JLabel studentButtonLabel;
    private javax.swing.JPanel studentButtonPanel;
    private javax.swing.JLabel studentFillLabel;
    private javax.swing.JPanel studentListPanel;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JTextField titleField;
    private javax.swing.JPanel topStudentPanel;
    private javax.swing.JPanel userinfo;
    // End of variables declaration//GEN-END:variables
}
