/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubricsevaluation;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import java.awt.Toolkit;

/**
 *
 * @author abdullah
 */
public class Test extends javax.swing.JFrame {
    
    private static final int WIDTH = Toolkit.getDefaultToolkit().getScreenSize().width;
    private static final int HEIGHT = Toolkit.getDefaultToolkit().getScreenSize().height;

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        this.setLocation((WIDTH-this.getWidth())/2, (HEIGHT-this.getHeight())/2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new RoundedPanel(25);
        homeButtonPanel = new RoundedPanel(25);
        homeLabel = new javax.swing.JLabel();
        coursesButtonPanel = new RoundedPanel(25);
        coursesLabel = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(25);

        jMenuItem1.setText("Delete");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Properties");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(48, 57, 82));
        jPanel1.setForeground(new java.awt.Color(48, 57, 82));
        jPanel1.setPreferredSize(new java.awt.Dimension(68, 494));

        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-home-64.png"))); // NOI18N

        javax.swing.GroupLayout homeButtonPanelLayout = new javax.swing.GroupLayout(homeButtonPanel);
        homeButtonPanel.setLayout(homeButtonPanelLayout);
        homeButtonPanelLayout.setHorizontalGroup(
            homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        homeButtonPanelLayout.setVerticalGroup(
            homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(homeButtonPanel);
        homeButtonPanel.setOpaque(false);

        coursesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubricsevaluation/icons8-book-64.png"))); // NOI18N

        javax.swing.GroupLayout coursesButtonPanelLayout = new javax.swing.GroupLayout(coursesButtonPanel);
        coursesButtonPanel.setLayout(coursesButtonPanelLayout);
        coursesButtonPanelLayout.setHorizontalGroup(
            coursesButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coursesLabel)
                .addContainerGap())
        );
        coursesButtonPanelLayout.setVerticalGroup(
            coursesButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(coursesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(coursesButtonPanel);
        coursesButtonPanel.setOpaque(false);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);
        jPanel1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
        jPanel2.setOpaque(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coursesButtonPanel;
    private javax.swing.JLabel coursesLabel;
    private javax.swing.JPanel homeButtonPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
